//REDUX CONSTANTS
export const FETCHING_DATA = 'FETCHING_DATA';
export const DATA_FAILURE = 'DATA_FAILURE';
export const DATA_SUCCESS = {
  ENTERPRISE: 'SUCCESS_ENTERPRISE',
  PERSON: 'SUCCESS_PERSON',
  INSCRIBED: 'SUCCESS_INSCRIBED',
};
